title:              ""
email:              zl679@cornell.edu
description:        Zhijing Li
author:             Zhijing
baseurl:            ""
url:                ""
copyright_name:     ""
# Social Profiles
twitter_username:   qino_sd
github_username:    tissue3
facebook_username:  zhijing.li.94
linkedin_username:

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll/scholar
  
scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending
  allow_locale_overrides: false
  group_by: none
  group_order: ascending

  source: ./
  bibliography: bibliography.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

